# GitHub Actions Cron settings
name: Run FABI BRW Bank Sync Bot

on:
  schedule:
    - cron: '0 23 * * *'    # Chạy lúc 6:00 AM giờ Việt Nam
    - cron: '30 1 * * *'    # Chạy lúc 8:30 AM giờ Việt Nam
    - cron: '30 4 * * *'    # Chạy lúc 11:30 AM giờ Việt Nam
    - cron: '30 6 * * *'    # Chạy lúc 1:30 PM giờ Việt Nam
    - cron: '30 9 * * *'    # Chạy lúc 4:30 PM giờ Việt Nam

  workflow_dispatch: # Bấm nút chạy thử bằng tay trên giao diện web GitHub

jobs:
  run-fabi-bot:
    runs-on: ubuntu-latest 
    
    # 🐳 Chạy trên môi trường Docker của chính Playwright
    container:
      image: mcr.microsoft.com/playwright:v1.44.0-jammy

    steps:
    # Bước 1: Kéo toàn bộ code từ kho lưu trữ GitHub của anh vào môi trường Docker
    - name: Checkout repository code
      uses: actions/checkout@v4

    # Bước 2: Cài đặt và sử dụng lệnh pip3 chuẩn xác cho hệ thống
    - name: Install dependencies
      run: |
        sudo apt-get update 
        pip3 install -r requirements.txt

    # Bước 3: Kích hoạt chạy con bot mã nguồn của anh
    - name: Execute Bank Switcher Task
      env:
        FABI_USERNAME: '${{ secrets.FABI_USERNAME }}'
        FABI_PASSWORD: '${{ secrets.FABI_PASSWORD }}'
        DISCORD_WEBHOOK_URL: '${{ secrets.DISCORD_WEBHOOK_URL }}'
      run: python3 -m tasks.bank_switcher